// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }



// 'use client';

// import { ReactNode } from 'react';
// import AppBar from '@mui/material/AppBar';
// import Toolbar from '@mui/material/Toolbar';
// import Typography from '@mui/material/Typography';
// import Drawer from '@mui/material/Drawer';
// import List from '@mui/material/List';
// import ListItem from '@mui/material/ListItem';
// import ListItemText from '@mui/material/ListItemText';
// import Box from '@mui/material/Box';
// import { ListItemButton } from '@mui/material';

// const drawerWidth = 220;

// const menuItems = [
//   'Home',
//   'Node',
//   'Application',
//   'Config',
//   'Device',
//   'Edge-Cloud Message',
//   'Service Grid',
//   'Kubernetes Policy',
//   'Customization',
// ];

// export default function RootLayout({ children }: { children: ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         {/* 顶部导航栏 */}
//         <AppBar
//           position="fixed"
//           sx={{ zIndex: (theme) => theme.zIndex.drawer + 1 }}
//         >
//           <Toolbar>
//             <Typography variant="h6" sx={{ flex: 1 }}>
//               KubeEdge Dashboard
//             </Typography>
//             {/* 右侧可以放空间选择、用户信息等 */}
//             <Typography variant="body1" sx={{ mr: 2 }}>
//               All NameSpace
//             </Typography>
//             <Typography variant="body1">admin</Typography>
//           </Toolbar>
//         </AppBar>

//         {/* 侧边栏 */}
//         <Drawer
//           variant="permanent"
//           sx={{
//             width: drawerWidth,
//             flexShrink: 0,
//             [`& .MuiDrawer-paper`]: { width: drawerWidth, boxSizing: 'border-box' },
//           }}
//         >
//           <List>
//             {menuItems.map((text) => (
//               <ListItem key={text} disablePadding>
//                 <ListItemButton>
//                   <ListItemText primary={text} />
//                 </ListItemButton>
//               </ListItem>
//               ))}
//           </List>
//         </Drawer>

//         {/* 内容区 */}
//         <Box
//           component="main"
//           sx={{ flexGrow: 1, bgcolor: '#f5f5f5', p: 3, ml: `${drawerWidth}px`, mt: '64px', minHeight: '100vh' }}
//         >
//           {children}
//         </Box>
//       </body>
//     </html>
//   );
// }


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
